#!/usr/bin/env bash
# Generate an aggregated third-party license notice for the statically linked
# Go dependencies, satisfying Apache-2.0 §4(d) / MIT / BSD attribution.
#
# This file is NOT committed — it is generated at image build and release time
# (see Dockerfile and .github/workflows/release.yml) so it can never drift from
# go.mod. Run locally only if you want to inspect it.
#
# Usage: scripts/gen-licenses.sh [output-file]   (default: THIRD_PARTY_LICENSES.txt)
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="${1:-THIRD_PARTY_LICENSES.txt}"
OWN=github.com/jesseheady/technician
# Pin for reproducible output — bumping this may legitimately change the result.
GOLICENSES_VERSION="${GOLICENSES_VERSION:-v1.6.0}"

# (Re)install when missing or when the binary's build-Go differs from the active
# toolchain: go-licenses resolves stdlib module info with build-time logic, so a
# stale binary fails on every std package ("does not have module info") after a
# Go upgrade. The install must be host-native (GOOS/GOARCH cleared for that one
# command) so the tool actually runs, but GOOS/GOARCH otherwise flow through to
# `go-licenses save`/`report` below, which honor them — a cross-compile's notice
# must reflect the target's dependency set, not the host's.
want="$(go env GOVERSION)"
have=""
if command -v go-licenses >/dev/null 2>&1; then
  have="$(go version -m "$(command -v go-licenses)" 2>/dev/null | awk 'NR==1{print $2}')"
fi
if [ -z "${have:-}" ] || [ "$have" != "$want" ]; then
  echo "installing go-licenses ${GOLICENSES_VERSION} (built for ${want})..." >&2
  env -u GOOS -u GOARCH go install "github.com/google/go-licenses@${GOLICENSES_VERSION}"
  PATH="$PATH:$(go env GOPATH)/bin"
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
go-licenses save ./... --save_path="$TMP/licenses" --ignore "$OWN" 2>/dev/null

{
  echo "Technician — Third-Party Software Notices"
  echo "========================================="
  echo
  echo "Technician statically links the Go modules listed below. Their license"
  echo "texts follow. All dependencies are permissively licensed (Apache-2.0,"
  echo "MIT, or BSD). Generated by scripts/gen-licenses.sh from go.mod."
  echo
  go-licenses report ./... --ignore "$OWN" 2>/dev/null \
    | awk -F',' '{printf "  %-70s %s\n", $1, $3}' | LC_ALL=C sort
  echo
  find "$TMP/licenses" -type f -print0 | LC_ALL=C sort -z | while IFS= read -r -d '' f; do
    mod="$(dirname "${f#"$TMP"/licenses/}")"
    echo
    echo "================================================================================"
    echo "$mod"
    echo "================================================================================"
    cat "$f"
    echo
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines, $(find "$TMP/licenses" -type f | wc -l | tr -d ' ') license files)"
